# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python_code\Longfier_Potel_De-Beer\code\combat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_combat_window(object):
    def setupUi(self, combat_window):
        combat_window.setObjectName("combat_window")
        combat_window.resize(1100, 834)
        self.attack_button = QtWidgets.QPushButton(combat_window)
        self.attack_button.setGeometry(QtCore.QRect(200, 510, 300, 120))
        self.attack_button.setObjectName("attack_button")
        self.run_button = QtWidgets.QPushButton(combat_window)
        self.run_button.setGeometry(QtCore.QRect(600, 650, 300, 120))
        self.run_button.setObjectName("run_button")
        self.bag_button = QtWidgets.QPushButton(combat_window)
        self.bag_button.setGeometry(QtCore.QRect(200, 650, 300, 120))
        self.bag_button.setObjectName("bag_button")
        self.pokemon_button = QtWidgets.QPushButton(combat_window)
        self.pokemon_button.setGeometry(QtCore.QRect(600, 510, 300, 120))
        self.pokemon_button.setObjectName("pokemon_button")

        self.retranslateUi(combat_window)
        QtCore.QMetaObject.connectSlotsByName(combat_window)

    def retranslateUi(self, combat_window):
        _translate = QtCore.QCoreApplication.translate
        combat_window.setWindowTitle(_translate("combat_window", "Combat"))
        self.attack_button.setText(_translate("combat_window", "ATTAQUE"))
        self.run_button.setText(_translate("combat_window", "FUITE"))
        self.bag_button.setText(_translate("combat_window", "SAC"))
        self.pokemon_button.setText(_translate("combat_window", "POKEMON"))

