# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'D:\Python_code\Longfier_Potel_De-Beer\code\echap.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_echap_window(object):
    def setupUi(self, echap_window):
        echap_window.setObjectName("echap_window")
        echap_window.resize(1000, 650)
        self.background_label = QtWidgets.QLabel(echap_window)
        self.background_label.setGeometry(QtCore.QRect(0, 0, 1000, 650))
        self.background_label.setPixmap(QtGui.QPixmap("ressources/echap_background.png"))
        self.background_label.setScaledContents(True)
        self.resume_button = QtWidgets.QPushButton(echap_window)
        self.resume_button.setGeometry(QtCore.QRect(50, 80, 400, 90))
        self.resume_button.setObjectName("resume_button")
        self.quit_button = QtWidgets.QPushButton(echap_window)
        self.quit_button.setGeometry(QtCore.QRect(50, 480, 400, 90))
        self.quit_button.setObjectName("quit_button")
        self.settings_button = QtWidgets.QPushButton(echap_window)
        self.settings_button.setGeometry(QtCore.QRect(50, 280, 400, 90))
        self.settings_button.setObjectName("settings_button")

        self.retranslateUi(echap_window)
        QtCore.QMetaObject.connectSlotsByName(echap_window)

    def retranslateUi(self, ehcap_window):
        _translate = QtCore.QCoreApplication.translate
        ehcap_window.setWindowTitle(_translate("echap_window", "Echap"))
        self.resume_button.setText(_translate("echap_window", "Continuer"))
        self.quit_button.setText(_translate("echap_window", "Quitter"))
        self.settings_button.setText(_translate("echap_window", "Paramètres"))

"""
class EchapWindow(QtWidgets.QMainWindow):  # Ou QtWidgets.QWidget selon vos besoins
    def __init__(self):
        super().__init__()
        self.ui = Ui_echap_window()
        self.ui.setupUi(self)
        self.setWindowTitle("Echap")
        self.ui.resume_button.clicked.connect(self.continuer)
        self.ui.quit_button.clicked.connect(self.quitter)
        self.ui.settings_button.clicked.connect(self.parametres)

"""
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    echap_window = QtWidgets.QWidget()
    ui = Ui_echap_window()
    ui.setupUi(echap_window)
    echap_window.show()
    sys.exit(app.exec_())